services:
  mongo:
    image: mongo:jammy
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=
    volumes:
      - /var/db_data/:/data/db/
    networks:
      - default
  nn:
    image: otchayanniy/beatheaven:version0.4
    restart: always
    container_name: nn
    networks:
      - default
  backend:
    image: arklim/beatheaven-backend:1.0
    restart: always
    container_name: backend
    ports:
      - 9432:9432
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=
      - MONGO_USER=
      - MONGO_PWD=
      - MONGO_COLLECTION=
      - NN_HOST=nn
      - NN_PORT=
      - API_KEY=
    depends_on:
      - mongo
      - nn
    volumes:
      - /var/backend_logs/:/var/logs
    networks:
      - default
volumes:
  mongo:

networks:
  default:
    driver: bridge
    